smooth_pmm_working_law <- function(eta_obs, eta_mis, donors) {
  delta <- outer(eta_obs, eta_mis, "-")
  dist2 <- delta^2

  scale <- min(
    stats::sd(eta_obs),
    stats::IQR(eta_obs) / 1.34,
    na.rm = TRUE
  )
  if (!is.finite(scale) || scale <= 0) {
    scale <- stats::sd(eta_obs)
  }
  h_floor <- max(1e-8 * stats::sd(eta_obs), 1e-12, na.rm = TRUE)
  h_rule <- max(0.9 * scale * length(eta_obs)^(-1 / 5), h_floor)

  lambda0 <- rep(0.5 / h_rule^2, length(eta_mis))
  log_weight0 <- -sweep(dist2, 2L, lambda0, "*")
  log_weight0 <- sweep(log_weight0, 2L, apply(log_weight0, 2L, max), "-")
  weight0 <- exp(log_weight0)
  weight0 <- sweep(weight0, 2L, colSums(weight0), "/")
  effective0 <- 1 / colSums(weight0^2)

  bandwidth <- h_rule * pmax(donors / pmax(effective0, 1e-8), 1e-4)^0.75
  lambda <- 0.5 / pmax(bandwidth, h_floor)^2
  log_weight <- -sweep(dist2, 2L, lambda, "*")
  log_weight <- sweep(log_weight, 2L, apply(log_weight, 2L, max), "-")
  weight <- exp(log_weight)
  weight <- sweep(weight, 2L, colSums(weight), "/")

  list(
    delta = delta,
    weight = weight,
    lambda = lambda,
    bandwidth = bandwidth,
    effective_donors = 1 / colSums(weight^2)
  )
}

#' Predictive mean matching for RW-PMM
#'
#' Uses ordinary MICE PMM donor selection while storing the realized donor and
#' a smooth all-donor working score for RW-PMM variance estimation.
#'
#' @inheritParams mice::mice.impute.pmm
#' @param donors The PMM donor-pool size used by `mice::matchindex()`.
#' @param matchtype,use.matcher PMM matching options.
#' @details Completed values are generated by the same hard donor-selection
#'   step as ordinary MICE PMM. The differentiable all-observed-donor law is a
#'   working law used only to construct the score required by `pool_rw()`; it
#'   does not generate the completed values. This method supports numeric
#'   variables and requires `tasks = "train"`.
#' @return A vector of imputed values.
#' @export
mice.impute.pmmrw <- function(y, ry, x, wy = NULL, task = "impute", model = NULL,
                              exclude = NULL, ridge = 1e-05, matchtype = 1L,
                              donors = 5L, use.matcher = FALSE, mlocal = 1L,
                              ...) {
  if (!is.null(exclude)) {
    stop("`pmmrw` does not currently support `exclude`.", call. = FALSE)
  }
  if (is.factor(y)) {
    stop("`pmmrw` currently supports numeric variables only.", call. = FALSE)
  }
  if (isTRUE(use.matcher)) {
    stop("`pmmrw` currently supports `use.matcher = FALSE` only.", call. = FALSE)
  }
  if (!identical(as.integer(mlocal), 1L)) {
    stop("`pmmrw` currently supports `mlocal = 1` only.", call. = FALSE)
  }
  if (is.null(wy)) {
    wy <- !ry
  }
  if (task != "train") {
    stop("`pmmrw` must be used with `tasks = 'train'`.", call. = FALSE)
  }
  if (is.null(model) || !is.environment(model)) {
    stop("`model` must be an environment; use `tasks = 'train'`.", call. = FALSE)
  }

  n <- length(y)
  row_id <- seq_len(n)
  x <- cbind(`(Intercept)` = 1, as.matrix(x))
  norm_draw <- utils::getFromNamespace(".norm.draw", "mice")
  parm <- norm_draw(y, ry, x, ridge = ridge, ...)
  beta_est <- drop(parm$coef)
  beta_draw <- drop(parm$beta)
  beta_hat <- beta_est
  beta_dot <- beta_draw

  if (matchtype == 0L) {
    beta_dot <- beta_hat
  } else if (matchtype == 2L) {
    beta_hat <- beta_dot
  }

  x_obs <- x[ry, , drop = FALSE]
  x_mis <- x[wy, , drop = FALSE]
  yhat_obs <- as.vector(x_obs %*% beta_hat)
  yhat_mis <- as.vector(x_mis %*% beta_dot)

  if (is.null(donors)) {
    donors <- round(length(yhat_obs) / 600 + 7)
  }
  donors <- max(1L, min(as.integer(donors), length(yhat_obs)))
  donor_pos <- mice::matchindex(yhat_obs, yhat_mis, donors)

  eta_obs <- as.vector(x_obs %*% beta_dot)
  eta_mis <- as.vector(x_mis %*% beta_dot)
  working <- smooth_pmm_working_law(eta_obs, eta_mis, donors)

  picked <- cbind(donor_pos, seq_len(sum(wy)))
  two_delta_weight <- 2 * working$delta * working$weight
  mean_derivative <- crossprod(two_delta_weight, x_obs) -
    sweep(x_mis, 1L, colSums(two_delta_weight), "*")
  realized_derivative <- sweep(
    x_obs[donor_pos, , drop = FALSE] - x_mis,
    1L,
    2 * working$delta[picked],
    "*"
  )
  score_mis <- sweep(
    realized_derivative - mean_derivative,
    1L,
    -working$lambda,
    "*"
  )

  sigma_hat <- as.numeric(parm$sigma)
  residual_obs <- y[ry] - as.vector(x_obs %*% beta_est)
  score_orig <- x_obs * (residual_obs / sigma_hat^2)
  information <- -crossprod(x_obs) / (sigma_hat^2 * n)
  d_obs <- t(-solve(information, t(score_orig)))

  pmm_score <- matrix(0, n, ncol(x), dimnames = list(NULL, colnames(x)))
  pmm_d <- matrix(0, n, ncol(x), dimnames = list(NULL, colnames(x)))
  pmm_score[wy, ] <- score_mis
  pmm_d[ry, ] <- d_obs

  donor_id <- rep(NA_integer_, n)
  donor_id[wy] <- row_id[ry][donor_pos]

  model$setup <- list(
    method = "pmmrw",
    n = sum(ry),
    task = task,
    donors = donors,
    matchtype = matchtype,
    ridge = ridge,
    working_law = "all_observed_donors",
    bandwidth_rule = "silverman_k_neff_0.75"
  )
  model$beta.hat <- beta_hat
  model$beta.dot <- beta_dot
  model$beta.work <- beta_dot
  model$sigma.dot <- sigma_hat
  model$xnames <- colnames(x)
  model$donor_id <- donor_id
  model$pmm_score <- pmm_score
  model$pmm_d <- pmm_d
  model$pmm_diagnostics <- c(
    mean_bandwidth = mean(working$bandwidth),
    mean_effective_donors = mean(working$effective_donors)
  )

  y[ry][donor_pos]
}

#' Extract PMM donor row IDs
#'
#' @param object A `mids` object created by `mice()` using `method = "pmmrw"`
#'   and `tasks = "train"`.
#' @param vars Optional PMM variable names. If omitted, all `pmmrw` variables
#'   are used.
#' @return For one PMM variable, an `n` by `m` integer matrix. Entries are `NA`
#'   for rows that were not imputed by PMM and the observed donor row number for
#'   PMM recipients. For multiple variables, a named list of such matrices.
#' @export
extract_donor_id <- function(object, vars = NULL) {
  if (!inherits(object, "mids")) {
    cli::cli_abort("{.arg object} must be a {.cls mids} object.")
  }
  if (is.null(object$models)) {
    cli::cli_abort("{.arg object} must contain models from {.code tasks = 'train'}.")
  }

  if (is.null(vars)) {
    vars <- names(object$method)[object$method == "pmmrw"]
  }
  if (length(vars) == 0L) {
    cli::cli_abort("No {.val pmmrw} variables were found.")
  }

  out <- lapply(vars, function(var) {
    if (!var %in% names(object$models)) {
      cli::cli_abort("No stored model found for {.field {var}}.")
    }
    donor_list <- lapply(seq_len(object$m), function(i) {
      donor <- object$models[[var]][[i]]$donor_id
      if (is.null(donor)) {
        cli::cli_abort(
          "No donor IDs were recorded for {.field {var}} imputation {i}."
        )
      }
      as.integer(donor)
    })
    mat <- do.call(cbind, donor_list)
    colnames(mat) <- paste0("imp", seq_len(object$m))
    mat
  })
  names(out) <- vars

  if (length(out) == 1L) out[[1L]] else out
}
